### PR TITLE
Metadata encrypted with message before sending to server

### PR DESCRIPTION
**Pull request by megatrond**
Possible downside: cache is now completely cleartext. Maybe not so bad?

We could add an option, --purge-cache, or the file can simply be deleted if you wanna. At least metadata is not exposed outside your own machine.

### CODE REVIEW

**Comment by megatrond** [comment]
Also, for some reason I can't figure out, messages are marked as read on server, but a sync will mark them as unread. probably something very obvious I'm missing.

**Comment by asbjornenge** [comment]
:+1: awesome! I'll get to this hopefully tomorrow!

**Comment by asbjornenge** [comment]
@megatrond So, finally did a review and it looks good :+1: There is however a few things...

### Marking as read

If we are serious about encrypting metadata; if a message is read or not would be an important part of that. This code (cli/read):

```
root.child(talk.config.user.name).child(message.id+'/read').set(true, function() {
    process.exit(0)
});
```

Sets a read property on the message in plain text on the server. Here, the message would have to be re-encrypted and replaced on the server.

### Undefined when reading old messages

When I try to read one of the old style messages it apparently has no id? At least the object user/undefined/read is set to true. Other than that old style messages still work. But for me it is OK to drop support for them, since there are only a few.

**Comment by asbjornenge** [comment]
Rydde litt... tror jeg lukker denne :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
